//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3634
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunglassCatiaPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SunglassCatiaPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap arrow_16 {
            get {
                object obj = ResourceManager.GetObject("arrow_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_161 {
            get {
                object obj = ResourceManager.GetObject("arrow_161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bg {
            get {
                object obj = ResourceManager.GetObject("bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap error_128 {
            get {
                object obj = ResourceManager.GetObject("error_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string IDS_ABOUT_ITEM_NAME {
            get {
                return ResourceManager.GetString("IDS_ABOUT_ITEM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Sunglass.
        /// </summary>
        internal static string IDS_ABOUT_ITEM_TOOLTIP {
            get {
                return ResourceManager.GetString("IDS_ABOUT_ITEM_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string IDS_BTN_CANCEL_CAPTION {
            get {
                return ResourceManager.GetString("IDS_BTN_CANCEL_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string IDS_BTN_CREATE_CAPTION {
            get {
                return ResourceManager.GetString("IDS_BTN_CREATE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string IDS_BTN_LOGIN_CAPTION {
            get {
                return ResourceManager.GetString("IDS_BTN_LOGIN_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string IDS_BTN_NO_CAPTION {
            get {
                return ResourceManager.GetString("IDS_BTN_NO_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string IDS_BTN_OK_CAPTION {
            get {
                return ResourceManager.GetString("IDS_BTN_OK_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        internal static string IDS_BTN_SYNC_CAPTION {
            get {
                return ResourceManager.GetString("IDS_BTN_SYNC_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string IDS_BTN_YES_CAPTION {
            get {
                return ResourceManager.GetString("IDS_BTN_YES_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2012 Design Tata Technologies Limited. All Rights Reserved.
        ///Sunglass for Catia is a Sunglass&lt;link&gt; project
        ///Sunglass Terms of User&lt;link&gt;.
        /// </summary>
        internal static string IDS_DLG_ABOUT_BODY {
            get {
                return ResourceManager.GetString("IDS_DLG_ABOUT_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string IDS_DLG_ABOUT_CAPTION {
            get {
                return ResourceManager.GetString("IDS_DLG_ABOUT_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string IDS_DLG_ABOUT_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDS_DLG_ABOUT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string IDS_DLG_ERROR_CAPTION {
            get {
                return ResourceManager.GetString("IDS_DLG_ERROR_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Error.
        /// </summary>
        internal static string IDS_DLG_ERROR_HEADER {
            get {
                return ResourceManager.GetString("IDS_DLG_ERROR_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunglass was unable to find a project associated with this model. Would you like to create a new Project for this 
        ///
        ///model or add it to an existing Project..
        /// </summary>
        internal static string IDS_DLG_FIRST_PUSH_BODY {
            get {
                return ResourceManager.GetString("IDS_DLG_FIRST_PUSH_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Project.
        /// </summary>
        internal static string IDS_DLG_FIRST_PUSH_HEADER {
            get {
                return ResourceManager.GetString("IDS_DLG_FIRST_PUSH_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Project updates to Sunglass.
        /// </summary>
        internal static string IDS_DLG_FIRST_PUSH_SUB_HEADER {
            get {
                return ResourceManager.GetString("IDS_DLG_FIRST_PUSH_SUB_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Successful.
        /// </summary>
        internal static string IDS_DLG_LOGIN_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDS_DLG_LOGIN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string IDS_DLG_LOGIN_HEADER {
            get {
                return ResourceManager.GetString("IDS_DLG_LOGIN_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to Sunglass.
        /// </summary>
        internal static string IDS_DLG_LOGIN_SUB_HEADER {
            get {
                return ResourceManager.GetString("IDS_DLG_LOGIN_SUB_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Sunglass.
        /// </summary>
        internal static string IDS_DLG_LOGIN_WELCOME {
            get {
                return ResourceManager.GetString("IDS_DLG_LOGIN_WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project aims to Aenean commodo ligula eget dolor.
        ///Aenean massa. Cum sociis natoque penatibus et magnis dis
        ///parturient montes, nascetur ridiculus mus. Donec quam felis,
        ///ultricies nec, pellentesque eu, pretium quis, sem..
        /// </summary>
        internal static string IDS_DLG_MSG_BODY {
            get {
                return ResourceManager.GetString("IDS_DLG_MSG_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string IDS_DLG_NEW_PROJECT_DESCRIPTION_LABEL {
            get {
                return ResourceManager.GetString("IDS_DLG_NEW_PROJECT_DESCRIPTION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional) add a project description.
        /// </summary>
        internal static string IDS_DLG_NEW_PROJECT_DESCRIPTION_PLACEHOLDER {
            get {
                return ResourceManager.GetString("IDS_DLG_NEW_PROJECT_DESCRIPTION_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        internal static string IDS_DLG_NEW_PROJECT_HEADER {
            get {
                return ResourceManager.GetString("IDS_DLG_NEW_PROJECT_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string IDS_DLG_NEW_PROJECT_SUMMARY_LABEL {
            get {
                return ResourceManager.GetString("IDS_DLG_NEW_PROJECT_SUMMARY_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a name for the Project.
        /// </summary>
        internal static string IDS_DLG_NEW_PROJECT_SUMMARY_PLACEHOLDER {
            get {
                return ResourceManager.GetString("IDS_DLG_NEW_PROJECT_SUMMARY_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Sunglass Project.
        /// </summary>
        internal static string IDS_DLG_NEW_PROJEСT_SUB_HEADER {
            get {
                return ResourceManager.GetString("IDS_DLG_NEW_PROJEСT_SUB_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments:.
        /// </summary>
        internal static string IDS_DLG_PROJECT_SYNC_DESCRIPTION_LABEL {
            get {
                return ResourceManager.GetString("IDS_DLG_PROJECT_SYNC_DESCRIPTION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional) any additional comments you wish to add.
        /// </summary>
        internal static string IDS_DLG_PROJECT_SYNC_DESCRIPTION_PLACEHOLDER {
            get {
                return ResourceManager.GetString("IDS_DLG_PROJECT_SYNC_DESCRIPTION_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Project.
        /// </summary>
        internal static string IDS_DLG_PROJECT_SYNC_HEADER {
            get {
                return ResourceManager.GetString("IDS_DLG_PROJECT_SYNC_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push project updates to Sunglass.
        /// </summary>
        internal static string IDS_DLG_PROJECT_SYNC_SUB_HEADER {
            get {
                return ResourceManager.GetString("IDS_DLG_PROJECT_SYNC_SUB_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary:.
        /// </summary>
        internal static string IDS_DLG_PROJECT_SYNC_SUMMARY_LABEL {
            get {
                return ResourceManager.GetString("IDS_DLG_PROJECT_SYNC_SUMMARY_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A brief summary of the changes made.
        /// </summary>
        internal static string IDS_DLG_PROJECT_SYNC_SUMMARY_PLACEHOLDER {
            get {
                return ResourceManager.GetString("IDS_DLG_PROJECT_SYNC_SUMMARY_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Project.
        /// </summary>
        internal static string IDS_DLG_PROJECTS_PULL_HEADER {
            get {
                return ResourceManager.GetString("IDS_DLG_PROJECTS_PULL_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Project to pull from Sunglass.
        /// </summary>
        internal static string IDS_DLG_PROJECTS_PULL_SUB_HEADER {
            get {
                return ResourceManager.GetString("IDS_DLG_PROJECTS_PULL_SUB_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Project.
        /// </summary>
        internal static string IDS_DLG_PROJECTS_PUSH_HEADER {
            get {
                return ResourceManager.GetString("IDS_DLG_PROJECTS_PUSH_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Project to push the current model to.
        /// </summary>
        internal static string IDS_DLG_PROJECTS_PUSH_SUB_HEADER {
            get {
                return ResourceManager.GetString("IDS_DLG_PROJECTS_PUSH_SUB_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Pull Successful.
        /// </summary>
        internal static string IDS_DLG_PULL_SUCCESSFULL_SUB_HEADER {
            get {
                return ResourceManager.GetString("IDS_DLG_PULL_SUCCESSFULL_SUB_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push model.
        /// </summary>
        internal static string IDS_DLG_PUSH_WARNING_SUB_HEADER {
            get {
                return ResourceManager.GetString("IDS_DLG_PUSH_WARNING_SUB_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunglass.
        /// </summary>
        internal static string IDS_DLG_SUNGLASS_MAIN_CAPTION {
            get {
                return ResourceManager.GetString("IDS_DLG_SUNGLASS_MAIN_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} model(s) were created
        ///{1} model(s) were updated
        ///{2} models(s) were deleted and removed from {7}
        ///{3} model(s) were skipped
        ///{4} space(s) were created
        ///{5} spaces(s) were updated
        ///{6} spaces(s) were deleted and removed from {8}.
        /// </summary>
        internal static string IDS_DLG_SYNC_PROJECT_SUCCESS_BODY {
            get {
                return ResourceManager.GetString("IDS_DLG_SYNC_PROJECT_SUCCESS_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Synced.
        /// </summary>
        internal static string IDS_DLG_SYNC_PROJECT_SUCCESS_HEADER {
            get {
                return ResourceManager.GetString("IDS_DLG_SYNC_PROJECT_SUCCESS_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Head updated to the latest version at {1}.
        /// </summary>
        internal static string IDS_DLG_SYNC_PROJECT_SUCCESS_SUB_HEADER {
            get {
                return ResourceManager.GetString("IDS_DLG_SYNC_PROJECT_SUCCESS_SUB_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string IDS_DLG_WARNING_CAPTION {
            get {
                return ResourceManager.GetString("IDS_DLG_WARNING_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunglass Warning.
        /// </summary>
        internal static string IDS_DLG_WARNING_HEADER {
            get {
                return ResourceManager.GetString("IDS_DLG_WARNING_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to login.
        /// </summary>
        internal static string IDS_ERR_LOGIN_FAIL {
            get {
                return ResourceManager.GetString("IDS_ERR_LOGIN_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create new project.
        /// </summary>
        internal static string IDS_ERR_NEW_PROJECT_CREATE_FAIL {
            get {
                return ResourceManager.GetString("IDS_ERR_NEW_PROJECT_CREATE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Exception.
        /// </summary>
        internal static string IDS_ERR_PROCESS_EXCEPTION {
            get {
                return ResourceManager.GetString("IDS_ERR_PROCESS_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid process.
        /// </summary>
        internal static string IDS_ERR_PROCESS_INVALID {
            get {
                return ResourceManager.GetString("IDS_ERR_PROCESS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Fail.
        /// </summary>
        internal static string IDS_ERR_PULL_FAIL {
            get {
                return ResourceManager.GetString("IDS_ERR_PULL_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload model fail.
        /// </summary>
        internal static string IDS_ERR_UPLOAD_FAIL {
            get {
                return ResourceManager.GetString("IDS_ERR_UPLOAD_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunglass.
        /// </summary>
        internal static string IDS_MAIN_GROUP_NAME {
            get {
                return ResourceManager.GetString("IDS_MAIN_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunglass commands.
        /// </summary>
        internal static string IDS_MAIN_GROUP_TOOLTIP {
            get {
                return ResourceManager.GetString("IDS_MAIN_GROUP_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem registering this dll: SWattr is null. \n\&quot;.
        /// </summary>
        internal static string IDS_MSG_DLL_REG_PROBLEM {
            get {
                return ResourceManager.GetString("IDS_MSG_DLL_REG_PROBLEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem unregistering this dll: .
        /// </summary>
        internal static string IDS_MSG_DLL_UNREG_PROBLEM {
            get {
                return ResourceManager.GetString("IDS_MSG_DLL_UNREG_PROBLEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem registering the function: \n\&quot;.
        /// </summary>
        internal static string IDS_MSG_FUNC_REG_PROBLEM {
            get {
                return ResourceManager.GetString("IDS_MSG_FUNC_REG_PROBLEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project associated with this model is no longer available. Would you like to create a new project or add to an existing Project?.
        /// </summary>
        internal static string IDS_MSG_PROJECT_MISSED {
            get {
                return ResourceManager.GetString("IDS_MSG_PROJECT_MISSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please save the model before calling this command.
        /// </summary>
        internal static string IDS_MSG_SAVE_MODEL {
            get {
                return ResourceManager.GetString("IDS_MSG_SAVE_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulls SolidWorks file from Sunglass server.
        /// </summary>
        internal static string IDS_PULL_ITEM_HINT {
            get {
                return ResourceManager.GetString("IDS_PULL_ITEM_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull.
        /// </summary>
        internal static string IDS_PULL_ITEM_NAME {
            get {
                return ResourceManager.GetString("IDS_PULL_ITEM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Model.
        /// </summary>
        internal static string IDS_PULL_ITEM_TOOLTIP {
            get {
                return ResourceManager.GetString("IDS_PULL_ITEM_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulling model....
        /// </summary>
        internal static string IDS_PULL_PROCESS_NAME {
            get {
                return ResourceManager.GetString("IDS_PULL_PROCESS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push SolidWorks file to Sunglass server.
        /// </summary>
        internal static string IDS_PUSH_ITEM_HINT {
            get {
                return ResourceManager.GetString("IDS_PUSH_ITEM_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push.
        /// </summary>
        internal static string IDS_PUSH_ITEM_NAME {
            get {
                return ResourceManager.GetString("IDS_PUSH_ITEM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Model.
        /// </summary>
        internal static string IDS_PUSH_ITEM_TOOLTIP {
            get {
                return ResourceManager.GetString("IDS_PUSH_ITEM_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushing model....
        /// </summary>
        internal static string IDS_PUSH_PROCESS_NAME {
            get {
                return ResourceManager.GetString("IDS_PUSH_PROCESS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunglass add-in detected virtual components in your assembly which are curently not supported. Would you like to proceed?.
        /// </summary>
        internal static string IDS_WRN_VIRTUAL_COMPONENTS_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("IDS_WRN_VIRTUAL_COMPONENTS_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual components detected.
        /// </summary>
        internal static string IDS_WRN_VIRTUAL_COMPS_DETECTED {
            get {
                return ResourceManager.GetString("IDS_WRN_VIRTUAL_COMPS_DETECTED", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap logout_128 {
            get {
                object obj = ResourceManager.GetObject("logout_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap plus_16 {
            get {
                object obj = ResourceManager.GetObject("plus_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sg_logo_128 {
            get {
                object obj = ResourceManager.GetObject("sg_logo_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap success_128 {
            get {
                object obj = ResourceManager.GetObject("success_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sync_enabled_128 {
            get {
                object obj = ResourceManager.GetObject("sync_enabled_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap warning_128 {
            get {
                object obj = ResourceManager.GetObject("warning_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
